### ISSUE TITLE
Vanilla install on Ubuntu error - Guice Exception: java.lang.IllegalArgumentException: script.disable_dynamic is not a supported setting, replace with fine-grained script settings.

### ISSUE THREAD

**Issue by adamst85** [geerlingguy/ansible-role-elasticsearch#11]
I get the below error after generating an Elasticsearch instance in Virtualbox. I fixed it by replacing 

`script.disable_dynamic: false` with

`script.inline: on` and
`script.indexed: on` as per the error message. Not sure if this error is happening for other people, but it would be a simple fix to change.

Guice Exception: java.lang.IllegalArgumentException: script.disable_dynamic is not a supported setting, replace with fine-grained script settings.
Dynamic scripts can be enabled for all languages and all operations by replacing `script.disable_dynamic: false` with `script.inline: on` and `script.indexed: on` in elasticsearch.yml

**Comment by rande** [comment]
yep, since an issue with the latest ES version

**Comment by bashcoder** [comment]
Same here on CentOS 6.7, and same fix worked. Happy to contribute a pull request if desired, @geerlingguy 

Reference:
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html

**Comment by geerlingguy** [comment]
@bashcoder - Sure thing, please send it and I'll review. I've been meaning to run through ELK-related roles and do some major cleanup lately; I've spent too much time on my LEMP/proxy roles lately :)

**Comment by geerlingguy** [comment]
Fixed in #13
