### ISSUE TITLE
rpm_key task fails when behind proxy because of HTTPS

### ISSUE THREAD

**Issue by Eronarn** [geerlingguy/ansible-role-elasticsearch#14]
I haven't run this playbook for several months. Looks like a recent commit broke it for 1.9/2.0 versions of Ansible: https://github.com/geerlingguy/ansible-role-elasticsearch/commit/0914a77bb287363591d6ba4ce0e2ec31c7807a0a

```
TASK [geerlingguy.elasticsearch : Add Elasticsearch GPG key.] ******************
fatal: [nrg-logstash]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported proxy scheme: https. Currently ansible only supports HTTP proxies."}
```

It's kind of absurd that a HTTPS URL is not supported by rpm_key in the first place. But until it is, there should be an alternative that doesn't require modifying the module or running a proxy just to get the playbook to complete.

**Comment by geerlingguy** [comment]
This seems to be working correctly in CentOS 7 with 1.9.4, at least: https://travis-ci.org/geerlingguy/ansible-role-elasticsearch/jobs/109232429#L830

I haven't tested with 2.x on CentOS 7, but I'll try running locally with an ELK stack provision on my Mac with 2.0.0.2.

**Comment by geerlingguy** [comment]
Ah... it sounds like you might be working behind a corporate proxy? In this case, please see upstream issue https://github.com/ansible/ansible/issues/10941 — there is a workaround, it seems, but I don't have any environment where I can test behind a proxy at this time, and in most of my projects, I don't add explicit support for proxies unless there's a related bug that doesn't add any extra complexity to the role.

In this case, I could maybe turn the GPG key URL into a variable, and then you could use the old URL... but that is a bit less secure, so I'd definitely still default to the https URL.

**Comment by Eronarn** [comment]
Yes, unfortunately I'm almost always running on a VPN that enforces proxy use (and I have no ability to change the proxy settings as per that ticket). For the time being, I made a local copy that I've made modifications to, but I'd recommend keeping as many role URLs parameterized as possible.

**Comment by geerlingguy** [comment]
Closing this issue as it's been over 2 years and no further updates/fixes.
