### ISSUE TITLE
Make configuration of ElasticSearch more dynamic

### ISSUE THREAD

**Issue by leifmadsen** [geerlingguy/ansible-role-elasticsearch#20]
Currently the usage of the `lineinfile` module just makes the configuration of ES somewhat awkward and more difficult than it really needs to be.

A better approach would be to use a template.

**Comment by leifmadsen** [comment]
I've added a PR for this issue, but it's not yet complete as I have to update the documentation, and go through the other open PRs to mark them as deprecated in favour of this one (assuming the approach is accepted).

**Comment by davidak** [comment]
The PR is merged so this should be closed.

**Comment by geerlingguy** [comment]
@davidak - Great, thanks for reminding me!
