### ISSUE TITLE
Elasticsearch 1.x

### ISSUE THREAD

**Issue by tripox** [geerlingguy/ansible-role-elasticsearch#26]
The most 'stable' release of the Drupal module, [Elasticsearch Connector](https://www.drupal.org/project/elasticsearch_connector), requires Elasticsearch 1.x installed.

I'd be nice to have an option between Elasticsearch 1.x and 2.x.

I'm not sure if this feature request belongs here or on [geerlingguy/drupal-vm](https://github.com/geerlingguy/drupal-vm).

**Comment by geerlingguy** [comment]
@tripox - It would be best to have an issue in this queue, since the ability to specify a version would have to be controlled by this Ansible role.

It might not be too hard to allow the choice between the two (though some configuration might need to change with a version difference).

**Comment by prydie** [comment]
[`torchbox/wagtail`](https://github.com/torchbox/wagtail) also requires 1.x so :+1: for multi-version support.

**Comment by korzh-nick** [comment]
```
diff --git a/provisioning/roles/geerlingguy.elasticsearch/defaults/main.yml b/provisioning/roles/geerlingguy.elasticsearch/defaults/main.yml
index 758877f..e27808a 100644
--- a/provisioning/roles/geerlingguy.elasticsearch/defaults/main.yml
+++ b/provisioning/roles/geerlingguy.elasticsearch/defaults/main.yml
@@ -3,3 +3,4 @@ elasticsearch_network_host: localhost
 elasticsearch_http_port: 9200
 elasticsearch_script_inline: true
 elasticsearch_script_indexed: true
+elasticsearch_version: 2.x
diff --git a/provisioning/roles/geerlingguy.elasticsearch/tasks/setup-Debian.yml b/provisioning/roles/geerlingguy.elasticsearch/tasks/setup-Debian.yml
index bafa0d5..ef4b4e0 100644
--- a/provisioning/roles/geerlingguy.elasticsearch/tasks/setup-Debian.yml
+++ b/provisioning/roles/geerlingguy.elasticsearch/tasks/setup-Debian.yml
@@ -4,11 +4,19 @@
     url: https://packages.elastic.co/GPG-KEY-elasticsearch
     state: present
 
-- name: Add Elasticsearch repository.
+- name: Add Elasticsearch repository.(2.x)
   apt_repository:
     repo: 'deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'
     state: present
     update_cache: yes
+  when: elasticsearch_version == '2.x'
+
+- name: Add Elasticsearch repository.(1.4)
+  apt_repository:
+    repo: 'deb http://packages.elastic.co/elasticsearch/1.4/debian stable main'
+    state: present
+    update_cache: yes
+  when: elasticsearch_version == '1.4'
 
 - name: Install Elasticsearch.
   apt: pkg=elasticsearch state=present
```

**Comment by davidak** [comment]
1.7 was EOL on 2017-01-16.

Source: https://www.elastic.co/support/eol

But you should support the current stable version 5.x.

**Comment by geerlingguy** [comment]
Yeah, definitely. I'm trying to get that done ASAP, maybe by end of day today!

But definitely not planning on supporting 1.x further—if someone really needs it, they can use an older role version at this point.
