### ISSUE TITLE
Add initial_master_nodes

### ISSUE THREAD

**Issue by in0rdr** [geerlingguy/ansible-role-elasticsearch#49]
Elasticsearch 7.x comes with new parameters for discovery of cluster nodes:
https://www.elastic.co/guide/en/elasticsearch/reference/current/discovery-settings.html

If `network.host: 0.0.0.0` is set, Elasticsearch will not start without setting `initial_master_nodes` as well:
```
#/etc/elasticsearch/elasticsearch.yml
cluster.initial_master_nodes:
  - "elastic0"
```

If this is not the case, Elasticsearch will fail to start with the following message:
```
[2019-07-03T14:23:13,130][ERROR][o.e.b.Bootstrap          ] [elastic0] node validation exception
[1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
```

I did not check on the other parameters, `seed_hosts` or `seed_providers`. Probably they could be implemented in the same "task". However, a single-node Elasticsearch bootstraps fine by defining `initial_master_nodes` only.

**Comment by in0rdr** [comment]
This could be resolved with https://github.com/geerlingguy/ansible-role-elasticsearch/issues/38 as well, because it concerns "append only" arguments for newer versions of Elasticsearch

**Comment by dale-c-anderson** [comment]
@in0rdr , agreed - https://github.com/geerlingguy/ansible-role-elasticsearch/issues/38 was a great suggestion. Simple and effective. 

Pull request has been submitted https://github.com/geerlingguy/ansible-role-elasticsearch/pull/54
