### ISSUE TITLE
Elasticsearch role forces restart

### ISSUE THREAD

**Issue by Eronarn** [geerlingguy/ansible-role-elasticsearch#5]
This is sort of a dupe of this issue: https://github.com/geerlingguy/ansible-role-nginx/issues/21

Likewise, your Elasticsearch role explicitly restarts the service at the end of it. This doesn't work well if you want to modify ES configuration in another role executed after yours (in my case, modifying /etc/sysconfig/elasticsearch to increase heap size). Anyone who really, definitely needs elasticsearch running before executing another role should probably split them into different plays.

**Comment by geerlingguy** [comment]
Closing this issue in favor of https://github.com/geerlingguy/ansible-role-elasticsearch/issues/7; it's not a direct duplicate, but for now I'm okay with the limitation of this role doing the restart at the end, as it makes things slightly less complicated in some scenarios, and it would require at least a minor version bump to change it.
