### ISSUE TITLE
Changing configuration values does not restart elasticsearch

### ISSUE THREAD

**Issue by jamieburchell** [geerlingguy/ansible-role-elasticsearch#53]
When changing any of the configuration values which cause a change to `elasticsearch.yml.j2`, the service is not restarted. There is a handler defined, but it doesn't appear to be used. Instead there is this task:

```
- name: Force a restart if configuration has changed.
  meta: flush_handlers
```

but this doesn't appear to do anything?

**Comment by geerlingguy** [comment]
You're correct... this task (https://github.com/geerlingguy/ansible-role-elasticsearch/blob/master/tasks/main.yml#L13-L22) should have a `notify: restart elasticsearch` on it... but it doesn't! Not sure how I've overlooked that in the past. I'll get this fixed.
