### ISSUE TITLE
Different heap size for jvm causes issue when starting the es service

### ISSUE THREAD

**Issue by goldpanic** [geerlingguy/ansible-role-elasticsearch#62]
Hello,

I couldn't start elasticsearch because of the heap map size that was different in min and max default variables in file defaults/main.yml. I mention that I adapted  the playbook a bit for my use but the main.

Currently `elasticsearch_heap_size_min` and `elasticsearch_heap_size_max` are not the same . But according to java configuration comment, it should be the same. I confirm that when I changed the value to match, i was able to start the service.

Below the comment that mention that point:

> You should always set the min and max JVM heap
> size to the same value. For example, to set
> the heap to 4 GB, set:
> -Xms4g
> -Xmx4g

**Comment by houstdav000** [comment]
It may also be worth noting that the official elasticsearch ansible role likewise implements an equivalency between the minimum and maximum allocation. 

See https://github.com/elastic/ansible-elasticsearch/blob/master/templates/jvm.options.j2
