### ISSUE TITLE
Recent Ansible moans about repository file permissions

### ISSUE THREAD

**Issue by nicenemo** [geerlingguy/ansible-role-elasticsearch#69]
A recent Ansible moans about repository file permissions.

When using this role I get:
``` 
[WARNING]: File
'/etc/apt/sources.list.d/artifacts_elastic_co_packages_7_x_apt.list' created
with default permissions '600'. The previous default was '666'. Specify 'mode'
to avoid this warning.
```

## solution

in the file _.../tasks/main.yml
add a line:

'```
mode: '0600'
```

> Same is true for your logstash repository, and probably a few others.

**Comment by geerlingguy** [comment]
I believe this change was walked back recently, and in addition, I did add `mode: 0660` recently. Closing this out—I'll hopefully tag a new release tonight.
