### ISSUE TITLE
variabilize path.data and path.log in elasticsearch.yml

### ISSUE THREAD

**Issue by wdesmarescaux** [geerlingguy/ansible-role-elasticsearch#72]
Hello all,
Thanks for your ansible module, it's very clear
Could you variabilize path.data and path.log in elasticsearch.yml jinja template ?

Thanks in advance

**Comment by nicenemo** [comment]
This can be done by https://github.com/geerlingguy/ansible-role-elasticsearch/pull/74

**Comment by pierrejego** [comment]
This one will do the same job #95  Thanks @chadek
