### ISSUE TITLE
Do not start Elasticsearch when it is configured to not be started

### ISSUE THREAD

**Issue by nicenemo** [geerlingguy/ansible-role-elasticsearch#76]
The current role always starts Elasticsearch, even it is configured not to be.
For cluster configuration I need to copy several files before the Elasticsearch can be started
See https://github.com/geerlingguy/ansible-role-elasticsearch/pull/75 with a more in depth explanation and Sample playbook.

Requires https://github.com/geerlingguy/ansible-role-elasticsearch/pull/74 to be able to configure the path for log files and data.

**Comment by bilalcaliskan** [comment]
what about writing post tasks for your playbooks to do extra steps?(stopping, starting, copying your own files etc)
