### ISSUE TITLE
"sorry, geerlingguy.ansible-role-elasticsearch was not found on https://galaxy.ansible.com/api/"

### ISSUE THREAD

**Issue by mikerev** [geerlingguy/ansible-role-elasticsearch#80]
`(venv) rev@devnull:/opt/.work/devnull$ ansible-galaxy install geerlingguy.ansible-role-elasticsearch
Starting galaxy role install process
- downloading role 'ansible-role-elasticsearch', owned by geerlingguy
[WARNING]: - geerlingguy.ansible-role-elasticsearch was NOT installed successfully: - sorry, geerlingguy.ansible-role-elasticsearch was not found on https://galaxy.ansible.com/api/.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
(venv) rev@devnull:/opt/.work/devnull$ ansible-galaxy --version
ansible-galaxy 2.10.4
  config file = /opt/.work/devnull/ansible.cfg
  configured module search path = ['/home/rev/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/.work/venv/lib/python3.8/site-packages/ansible
  executable location = /opt/.work/venv/bin/ansible-galaxy
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
(venv) rev@devnull:/opt/.work/devnull$ ansible --version
ansible 2.10.4
  config file = /opt/.work/devnull/ansible.cfg
  configured module search path = ['/home/rev/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/.work/venv/lib/python3.8/site-packages/ansible
  executable location = /opt/.work/venv/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
(venv) rev@devnull:/opt/.work/devnull$ `

looks like this issue occurred on other repos due to the ansible-role prefix?

**Comment by mikerev** [comment]
ubuntu 20.04

**Comment by TrueXakeP** [comment]
You have error in your Install command. It should be `ansible-galaxy install geerlingguy.elasticsearch`

**Comment by mikerev** [comment]
> You have error in your Install command. It should be `ansible-galaxy install geerlingguy.elasticsearch`

doh, ty. assumed from some other issue i found from another galaxy related repo. ty!
