### ISSUE TITLE
Unable to install specific version of elastic-search

### ISSUE THREAD

**Issue by umeshauv** [geerlingguy/ansible-role-elasticsearch#81]
When I try to install version 7.10.1,  I get the following error.
TASK [geerlingguy.elasticsearch : Install Elasticsearch.] ***********************************************************
fatal: [rabbitmq]: FAILED! => changed=false
  msg: |-
    Failure talking to yum: failure: repodata/repomd.xml from elasticsearch-7.10.1: [Errno 256] No more mirrors to try.
    https://artifacts.elastic.co/packages/7.10.1/yum/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

I have passed elasticsearch_version: '7.10.1'.

**Comment by bilalcaliskan** [comment]
@umeshauv currently that role does not permit you to specify specific version. It installs the latest version from elasticsearch 7.x repo on both RedHat and Debian. I will create a PR for that issue tomorrow.
